# OS / Maker ID
OS_ID_OFFSET = 0
OS_ID_BITS = 10
MILLA_OS_ID = 1

# Version
VERSION_OFFSET = 10
VERSION_BITS = 14
MILLA_VERSION = 1

# Font Size
FONT_SIZE_OFFSET = 24
FONT_SIZE_BITS = 5
DEFAULT_FONT_SIZE = 1

# Chunk Structure
CHUNK_SIZE_BITS = 4096
X_BITS = 16
Y_BITS = 48
Z_BITS = 4032
PAYLOAD_BITS = 3999
TWEAK_BITS = 1
PTR_BITS = 32
