# OS / Maker ID
OS_ID_OFFSET = 0
OS_ID_BITS = 10
MILLA_OS_ID = 1

# Version
VERSION_OFFSET = 10
VERSION_BITS = 14
MILLA_VERSION = 1

# Font Size
FONT_SIZE_OFFSET = 24
FONT_SIZE_BITS = 5
DEFAULT_FONT_SIZE = 1

# Chunk Structure
CHUNK_SIZE_BYTES = 512
X_BYTES = 2
Y_BYTES = 6
Z_BYTES = 504
PAYLOAD_BYTES = 500
PTR_BYTES = 4
